#############################################################################
# Makefile for building: TextLocoViewer
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Oct 30 02:15:53 2012
# Project:  TextLocoViewer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile TextLocoViewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -pthread -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pthread -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/local/include/opencv -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu /usr/local/lib/libopencv_core.so -pthread -L/usr/local/lib -llcm -lgthread-2.0 -lrt -lglib-2.0 -L -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		tileviewer.cpp \
		handler.cpp \
		lcmthread.cpp \
		clickablegraphicsview.cpp moc_tileviewer.cpp \
		moc_handler.cpp \
		moc_lcmthread.cpp \
		moc_clickablegraphicsview.cpp
OBJECTS       = main.o \
		tileviewer.o \
		handler.o \
		lcmthread.o \
		clickablegraphicsview.o \
		moc_tileviewer.o \
		moc_handler.o \
		moc_lcmthread.o \
		moc_clickablegraphicsview.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TextLocoViewer.pro
QMAKE_TARGET  = TextLocoViewer
DESTDIR       = 
TARGET        = TextLocoViewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_tileviewer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TextLocoViewer.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile TextLocoViewer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TextLocoViewer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TextLocoViewer1.0.0 || $(MKDIR) .tmp/TextLocoViewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TextLocoViewer1.0.0/ && $(COPY_FILE) --parents tileviewer.h handler.h lcmthread.h clickablegraphicsview.h .tmp/TextLocoViewer1.0.0/ && $(COPY_FILE) --parents main.cpp tileviewer.cpp handler.cpp lcmthread.cpp clickablegraphicsview.cpp .tmp/TextLocoViewer1.0.0/ && $(COPY_FILE) --parents tileviewer.ui .tmp/TextLocoViewer1.0.0/ && (cd `dirname .tmp/TextLocoViewer1.0.0` && $(TAR) TextLocoViewer1.0.0.tar TextLocoViewer1.0.0 && $(COMPRESS) TextLocoViewer1.0.0.tar) && $(MOVE) `dirname .tmp/TextLocoViewer1.0.0`/TextLocoViewer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TextLocoViewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_tileviewer.cpp moc_handler.cpp moc_lcmthread.cpp moc_clickablegraphicsview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tileviewer.cpp moc_handler.cpp moc_lcmthread.cpp moc_clickablegraphicsview.cpp
moc_tileviewer.cpp: lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		tileviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tileviewer.h -o moc_tileviewer.cpp

moc_handler.cpp: lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		tileviewer.h \
		handler.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) handler.h -o moc_handler.cpp

moc_lcmthread.cpp: lcmthread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) lcmthread.h -o moc_lcmthread.cpp

moc_clickablegraphicsview.cpp: tileviewer.h \
		lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		clickablegraphicsview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clickablegraphicsview.h -o moc_clickablegraphicsview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_tileviewer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_tileviewer.h
ui_tileviewer.h: tileviewer.ui
	/usr/bin/uic-qt4 tileviewer.ui -o ui_tileviewer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp tileviewer.h \
		lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		handler.h \
		lcmthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tileviewer.o: tileviewer.cpp tileviewer.h \
		lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		ui_tileviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tileviewer.o tileviewer.cpp

handler.o: handler.cpp handler.h \
		lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp \
		tileviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handler.o handler.cpp

lcmthread.o: lcmthread.cpp lcmthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lcmthread.o lcmthread.cpp

clickablegraphicsview.o: clickablegraphicsview.cpp clickablegraphicsview.h \
		tileviewer.h \
		lcmtypes/cpp/lcmtypes/text_loco/tile_to_image_t.hpp \
		lcmtypes/cpp/lcmtypes/text_loco/tile_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_t.hpp \
		lcmtypes/cpp/lcmtypes/bot_core/image_metadata_t.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clickablegraphicsview.o clickablegraphicsview.cpp

moc_tileviewer.o: moc_tileviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tileviewer.o moc_tileviewer.cpp

moc_handler.o: moc_handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_handler.o moc_handler.cpp

moc_lcmthread.o: moc_lcmthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lcmthread.o moc_lcmthread.cpp

moc_clickablegraphicsview.o: moc_clickablegraphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clickablegraphicsview.o moc_clickablegraphicsview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

