/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _text_loco_tile_set_t_h
#define _text_loco_tile_set_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "lcmtypes/text_loco_tile_t.h"
typedef struct _text_loco_tile_set_t text_loco_tile_set_t;
struct _text_loco_tile_set_t
{
    int64_t    utime;
    int64_t    linked_image_utime;
    int32_t    num_tiles;
    text_loco_tile_t *tiles;
};

text_loco_tile_set_t   *text_loco_tile_set_t_copy(const text_loco_tile_set_t *p);
void text_loco_tile_set_t_destroy(text_loco_tile_set_t *p);

typedef struct _text_loco_tile_set_t_subscription_t text_loco_tile_set_t_subscription_t;
typedef void(*text_loco_tile_set_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const text_loco_tile_set_t *msg, void *user);

int text_loco_tile_set_t_publish(lcm_t *lcm, const char *channel, const text_loco_tile_set_t *p);
text_loco_tile_set_t_subscription_t* text_loco_tile_set_t_subscribe(lcm_t *lcm, const char *channel, text_loco_tile_set_t_handler_t f, void *userdata);
int text_loco_tile_set_t_unsubscribe(lcm_t *lcm, text_loco_tile_set_t_subscription_t* hid);
int text_loco_tile_set_t_subscription_set_queue_capacity(text_loco_tile_set_t_subscription_t* subs,
                              int num_messages);


int  text_loco_tile_set_t_encode(void *buf, int offset, int maxlen, const text_loco_tile_set_t *p);
int  text_loco_tile_set_t_decode(const void *buf, int offset, int maxlen, text_loco_tile_set_t *p);
int  text_loco_tile_set_t_decode_cleanup(text_loco_tile_set_t *p);
int  text_loco_tile_set_t_encoded_size(const text_loco_tile_set_t *p);

// LCM support functions. Users should not call these
int64_t __text_loco_tile_set_t_get_hash(void);
int64_t __text_loco_tile_set_t_hash_recursive(const __lcm_hash_ptr *p);
int     __text_loco_tile_set_t_encode_array(void *buf, int offset, int maxlen, const text_loco_tile_set_t *p, int elements);
int     __text_loco_tile_set_t_decode_array(const void *buf, int offset, int maxlen, text_loco_tile_set_t *p, int elements);
int     __text_loco_tile_set_t_decode_array_cleanup(text_loco_tile_set_t *p, int elements);
int     __text_loco_tile_set_t_encoded_array_size(const text_loco_tile_set_t *p, int elements);
int     __text_loco_tile_set_t_clone_array(const text_loco_tile_set_t *p, text_loco_tile_set_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
