"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class reference_line_segment_t(object):
    __slots__ = ["start", "end", "reference_origin"]

    def __init__(self):
        self.start = [ 0.0 for dim0 in range(3) ]
        self.end = [ 0.0 for dim0 in range(3) ]
        self.reference_origin = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(reference_line_segment_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.start[:3]))
        buf.write(struct.pack('>3d', *self.end[:3]))
        buf.write(struct.pack('>3d', *self.reference_origin[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != reference_line_segment_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return reference_line_segment_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = reference_line_segment_t()
        self.start = struct.unpack('>3d', buf.read(24))
        self.end = struct.unpack('>3d', buf.read(24))
        self.reference_origin = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if reference_line_segment_t in parents: return 0
        tmphash = (0xfc2d743d6fad96fa) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if reference_line_segment_t._packed_fingerprint is None:
            reference_line_segment_t._packed_fingerprint = struct.pack(">Q", reference_line_segment_t._get_hash_recursive([]))
        return reference_line_segment_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

