"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import tile_t

class tile_set_t(object):
    __slots__ = ["utime", "linked_image_utime", "num_tiles", "tiles"]

    def __init__(self):
        self.utime = 0
        self.linked_image_utime = 0
        self.num_tiles = 0
        self.tiles = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(tile_set_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqi", self.utime, self.linked_image_utime, self.num_tiles))
        for i0 in range(self.num_tiles):
            self.tiles[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != tile_set_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tile_set_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tile_set_t()
        self.utime, self.linked_image_utime, self.num_tiles = struct.unpack(">qqi", buf.read(20))
        self.tiles = []
        for i0 in range(self.num_tiles):
            self.tiles.append(tile_t.tile_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tile_set_t in parents: return 0
        newparents = parents + [tile_set_t]
        tmphash = (0xe26757c7e01cd7f8+ tile_t.tile_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tile_set_t._packed_fingerprint is None:
            tile_set_t._packed_fingerprint = struct.pack(">Q", tile_set_t._get_hash_recursive([]))
        return tile_set_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

