"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import tile_t

class tile_to_image_t(object):
    __slots__ = ["utime", "tile", "image_utime", "x", "y"]

    def __init__(self):
        self.utime = 0
        self.tile = None
        self.image_utime = 0
        self.x = 0
        self.y = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(tile_to_image_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        self.tile._encode_one(buf)
        buf.write(struct.pack(">qqq", self.image_utime, self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != tile_to_image_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tile_to_image_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tile_to_image_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.tile = tile_t.tile_t._decode_one(buf)
        self.image_utime, self.x, self.y = struct.unpack(">qqq", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tile_to_image_t in parents: return 0
        newparents = parents + [tile_to_image_t]
        tmphash = (0x7fc331aa43705446+ tile_t.tile_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tile_to_image_t._packed_fingerprint is None:
            tile_to_image_t._packed_fingerprint = struct.pack(">Q", tile_to_image_t._get_hash_recursive([]))
        return tile_to_image_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

